/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.11-branch-eskatos_kotlin_embedded_2_0_20-20240905102145+0000/samples
 */
