/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11-branch-eskatos_kotlin_embedded_2_0_20-20240905102145+0000/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "backend-template"


