/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.ajcode404

import io.github.ajcode404.MessageUtils
import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class MessageUtilsTest {
    @Test fun testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage())
    }
}
